name: Auto Delete Repository

on:
  schedule:
    - cron: '0 0 19 2 *'
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Repository
        run: |
          CURRENT_DATE=$(date +%Y-%m-%d)
          TARGET_DATE="2026-02-19"
          if [[ "$CURRENT_DATE" == "$TARGET_DATE" ]]; then
            curl -X DELETE \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}
          fi
